
%%{init: {
  'themeVariables': {
    'fontSize': '14pt'
    },

  'quadrantChart': { 'chartWidth': 900, 'chartHeight': 900 }
}}%%

quadrantChart
  title Influence vs Interest for MCP-Geo Stakeholders
  x-axis Low interest --> High interest
  y-axis Low influence --> High influence
  quadrant-1 High influence / High interest
  quadrant-2 Low influence / High interest
  quadrant-3 Low influence / Low interest
  quadrant-4 High influence / Low interest

  "Central gov" : [0.78, 0.90]
  "Nat. mapping/statistics" : [0.72, 0.88]
  "Emergency services" : [0.80, 0.85]
  "Geo firms" : [0.74, 0.83]
  "Local authorities" : [0.82, 0.62]
  "Academia & research" : [0.78, 0.42]
  "Consultancies & integrators" : [0.62, 0.60]
  "Funders" : [0.55, 0.82]
  "Transport" : [0.60, 0.70]
  "Utilities" : [0.50, 0.78]
  "Environmental NGOs" : [0.62, 0.35]
  "Open-source" : [0.75, 0.40]
