#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.agent_control_common import (  # noqa: E402
    DEFAULT_ACTIVE_MODE_MANIFEST_PATH,
    DEFAULT_OUTPUT_ROOT,
    build_control_vault,
    utc_now,
)
from scripts.obsidian_cli import (  # noqa: E402
    DEFAULT_OBSIDIAN_APP,
    DEFAULT_OBSIDIAN_USER_DATA,
    preflight,
)

ROOT_FILES = (
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    ".github/copilot-instructions.md",
    "CONTEXT.md",
    "PROGRESS.MD",
)

CONTROL_HOME = "Obsidian/MCP Geo Agent Control/00 Home/00 - Agent Home.md"
CONTROL_FOCUS = "Obsidian/MCP Geo Agent Control/10 State/Current Focus.md"
CONTROL_QUEUE = "Obsidian/MCP Geo Agent Control/10 State/Work Queue.md"
CONTROL_VERIFY = "Obsidian/MCP Geo Agent Control/10 State/Verification.md"
CONTROL_REPO_MAP = "Obsidian/MCP Geo Agent Control/20 Generated/Repo Map Digest.md"
CONTROL_RELEASE = "Obsidian/MCP Geo Agent Control/20 Generated/Release Summary.md"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Switch the repo agent-control mode.")
    parser.add_argument(
        "--mode",
        choices=["classic", "obsidian"],
        required=True,
        help="Agent-control mode to apply.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Agent control vault root.",
    )
    parser.add_argument(
        "--mode-manifest",
        type=Path,
        default=DEFAULT_ACTIVE_MODE_MANIFEST_PATH,
        help="Machine-readable active-mode manifest path.",
    )
    parser.add_argument(
        "--app-path",
        type=Path,
        default=DEFAULT_OBSIDIAN_APP,
        help="Obsidian app bundle path used for CLI preflight.",
    )
    parser.add_argument(
        "--cli-path",
        type=Path,
        default=None,
        help="Explicit Obsidian CLI binary path override.",
    )
    parser.add_argument(
        "--user-data-path",
        type=Path,
        default=DEFAULT_OBSIDIAN_USER_DATA,
        help="Obsidian user-data directory used to detect updated runtime packages.",
    )
    parser.add_argument(
        "--require-cli",
        action="store_true",
        help="Fail the switch if the Obsidian CLI preflight is not ready.",
    )
    return parser


def git_stdout(repo_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout


def read_head_file(repo_root: Path, rel_path: str) -> str:
    return git_stdout(repo_root, "show", f"HEAD:{rel_path}")


def head_commit(repo_root: Path) -> str:
    return git_stdout(repo_root, "rev-parse", "HEAD").strip()


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def cli_status_line(cli_preflight: dict[str, Any]) -> str:
    if cli_preflight.get("ready"):
        return "- Obsidian CLI preflight: `ready`."
    issues = cli_preflight.get("issues", [])
    if not issues:
        return "- Obsidian CLI preflight: `unknown`."
    first = issues[0]
    return f"- Obsidian CLI preflight: `{first['code']}` ({first['message']})"


def render_obsidian_agents(cli_preflight: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# MCP Geo Agent Control",
            "",
            "This repository is currently in `obsidian` agent-control mode.",
            "This file is generated by `python3 scripts/switch_agent_mode.py --mode obsidian`.",
            "",
            "## Read Order",
            f"1. `{CONTROL_HOME}`",
            f"2. `{CONTROL_FOCUS}`",
            f"3. `{CONTROL_QUEUE}`",
            f"4. `{CONTROL_VERIFY}`",
            f"5. `{CONTROL_REPO_MAP}`",
            "",
            "## Defaults",
            "- Do not default to reading `CHANGELOG.md`; use the generated release digest instead.",
            f"- Preferred release summary: `{CONTROL_RELEASE}`",
            "- Use `python3 scripts/validate_agent_control.py` to verify vault and CLI readiness.",
            cli_status_line(cli_preflight),
            "",
        ]
    )


def render_obsidian_claude() -> str:
    return "\n".join(
        [
            "@AGENTS.md",
            "",
            "## Claude adapter",
            "- Follow the generated root `AGENTS.md` first.",
            "",
        ]
    )


def render_obsidian_gemini() -> str:
    return "\n".join(
        [
            "@AGENTS.md",
            "",
            "## Gemini adapter",
            "- Follow the generated root `AGENTS.md` first.",
            "",
        ]
    )


def render_obsidian_copilot() -> str:
    return "\n".join(
        [
            "# Copilot instructions (mcp-geo, obsidian mode)",
            "",
            "Follow the generated root `AGENTS.md` in this repository.",
            f"Primary control surface: `{CONTROL_HOME}`",
            "",
        ]
    )


def render_context_shim(cli_preflight: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# MCP Geo Context (Obsidian Mode Compatibility Summary)",
            "",
            "This compatibility summary is generated by `scripts/switch_agent_mode.py`.",
            "The full root tracker is not the default read path while `obsidian` mode is active.",
            "",
            "## Read Instead",
            f"- `{CONTROL_HOME}`",
            f"- `{CONTROL_FOCUS}`",
            f"- `{CONTROL_VERIFY}`",
            "",
            "## Current CLI Status",
            cli_status_line(cli_preflight),
            "",
            "## Notes",
            (
                "- Switch back to `classic` mode to restore the full tracked "
                "context files from `HEAD`."
            ),
            "",
        ]
    )


def render_progress_shim(cli_preflight: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# MCP Geo Progress (Obsidian Mode Compatibility Summary)",
            "",
            "This compatibility summary is generated by `scripts/switch_agent_mode.py`.",
            "The canonical work queue for `obsidian` mode lives in the control vault.",
            "",
            "## Read Instead",
            f"- `{CONTROL_QUEUE}`",
            f"- `{CONTROL_VERIFY}`",
            f"- `{CONTROL_RELEASE}`",
            "",
            "## Current CLI Status",
            cli_status_line(cli_preflight),
            "",
            "## Notes",
            "- Switch back to `classic` mode to restore the full tracked progress log from `HEAD`.",
            "",
        ]
    )


def write_obsidian_mode(repo_root: Path, cli_preflight: dict[str, Any]) -> None:
    rendered = {
        "AGENTS.md": render_obsidian_agents(cli_preflight),
        "CLAUDE.md": render_obsidian_claude(),
        "GEMINI.md": render_obsidian_gemini(),
        ".github/copilot-instructions.md": render_obsidian_copilot(),
        "CONTEXT.md": render_context_shim(cli_preflight),
        "PROGRESS.MD": render_progress_shim(cli_preflight),
    }
    for rel_path, content in rendered.items():
        write_text(repo_root / rel_path, content)


def restore_classic_mode(repo_root: Path) -> None:
    for rel_path in ROOT_FILES:
        write_text(repo_root / rel_path, read_head_file(repo_root, rel_path))


def write_mode_manifest(
    manifest_path: Path,
    *,
    mode: str,
    cli_preflight: dict[str, Any] | None,
    repo_root: Path,
) -> dict[str, Any]:
    payload = {
        "mode": mode,
        "updated_at": utc_now(),
        "head_commit": head_commit(repo_root),
        "control_vault_root": str(repo_root / "Obsidian" / "MCP Geo Agent Control"),
        "root_files": list(ROOT_FILES),
        "default_read_order": [
            CONTROL_HOME,
            CONTROL_FOCUS,
            CONTROL_QUEUE,
            CONTROL_VERIFY,
            CONTROL_REPO_MAP,
        ],
        "cli_preflight": cli_preflight,
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload


def switch_mode(
    repo_root: Path,
    *,
    mode: str,
    output_root: Path,
    mode_manifest_path: Path,
    app_path: Path,
    user_data_path: Path,
    cli_path: Path | None,
    require_cli: bool,
) -> dict[str, Any]:
    control_manifest_path = repo_root / "data" / "agent_control" / "control_vault_manifest.json"
    build_control_vault(
        repo_root,
        output_root=output_root,
        manifest_path=control_manifest_path,
    )
    cli_preflight = preflight(
        output_root,
        app_path=app_path,
        user_data_path=user_data_path,
        cli_path=cli_path,
    )
    if mode == "obsidian":
        if require_cli and not cli_preflight.get("ready"):
            first = cli_preflight["issues"][0]
            raise ValueError(f"{first['code']}: {first['message']}")
        write_obsidian_mode(repo_root, cli_preflight)
    else:
        restore_classic_mode(repo_root)
    return write_mode_manifest(
        mode_manifest_path,
        mode=mode,
        cli_preflight=cli_preflight,
        repo_root=repo_root,
    )


def main() -> int:
    args = build_parser().parse_args()
    manifest = switch_mode(
        REPO_ROOT,
        mode=args.mode,
        output_root=args.output_root,
        mode_manifest_path=args.mode_manifest,
        app_path=args.app_path,
        user_data_path=args.user_data_path,
        cli_path=args.cli_path,
        require_cli=args.require_cli,
    )
    print(f"Switched agent mode to {manifest['mode']}")
    print(f"Mode manifest: {args.mode_manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
